### ISSUE TITLE
Add dir to classpath permanently

### ISSUE THREAD

**Issue by james64** [alexarchambault/jupyter-scala#37] opened 2015-12-09 11:00 UTC
Hey,

I try to add new dependencies permanently so I do not need to add them every time. I rewrite jupyter-scala bash script. This does not work:

exec "$JAVACMD" \
     ${JVM_OPT} \
     -cp "${PROG_HOME}/lib/*${PSEP}/path/to/my/dir/*${CLASSPATH_SUFFIX}" \
...

Whatever is after ${PSEP} is not on classpath. I wonder how this PSEP should be used:

Path separator used in EXTRA_CLASSPATH
PSEP=":"

Is there any other way how you would do this?

**Comment by james64** [comment] 2015-12-09 11:11
export EXTRA_CLASSPATH is not working either. I'll try to experiment more

**Comment by alexarchambault** [comment] 2015-12-12 18:21
Duplicate of https://github.com/alexarchambault/jupyter-scala/issues/33.

@james64 Putting extra JARs as is in the classpath of the kernel (I mean, of the Java program launched as the kernel) can't work as is, as the classpath (the classloader to be specific) is somehow cleaned for the execution of user code. But allowing to add things to the classpath globally is something I'd like to add in the future (as soon as I'll give some love to jupyter-scala again, in a few weeks I hope).

**Closed by alexarchambault** 2015-12-12 18:21 UTC

**Comment by james64** [comment] 2015-12-15 17:53
Thanks for clarification. Just to be sure. Does this mean that one is not able to add classpath entry to kernel classloader manually on runtime? This is not a global setting but would still help... thanks!
