### ISSUE TITLE
Error downloading notebook as scala

### ISSUE THREAD

**Issue by ittayd** [alexarchambault/jupyter-scala#31] opened 2015-10-13 10:47 UTC
Trying to download as scala, a new tab opens with: 
500 : Internal Server Error
The error was:
nbconvert failed: FileExtension trait 'file_extension' does not begin with a dot: u'scala'

**Comment by alexarchambault** [comment] 2015-10-21 08:43
Duplicate of https://github.com/alexarchambault/jupyter-scala/issues/26

**Closed by alexarchambault** 2015-10-21 08:43 UTC
